export const Actions = {
    //Board
    FETCH_BOARD_START: 'FETCH_BOARD_START',
    FETCH_BOARD_FAIL: 'FETCH_BOARD_FAIL',
    FETCH_BOARD_SUCCESS: 'FETCH_BOARD_SUCCESS',

    ADD_BOARD_START: 'ADD_BOARD_START',
    ADD_BOARD_FAIL: 'ADD_BOARD_FAIL',
    ADD_BOARD_SUCCESS: 'ADD_BOARD_SUCCESS',

    REMOVE_BOARD_START: 'REMOVE_BOARD_START',
    REMOVE_BOARD_FAIL: 'REMOVE_BOARD_FAIL',
    REMOVE_BOARD_SUCCESS: 'REMOVE_BOARD_SUCCESS',

    //Single Board
    FETCH_SINGLE_BOARD_START: 'FETCH_SINGLE_BOARD_START',
    FETCH_SINGLE_BOARD_FAIL: 'FETCH_SINGLE_BOARD_FAIL',
    FETCH_SINGLE_BOARD_SUCCESS: 'FETCH_SINGLE_BOARD_SUCCESS',

    //List
    ADD_LIST_START: 'ADD_LIST_START',
    ADD_LIST_FAIL: 'ADD_LIST_FAIL',
    ADD_LIST_SUCCESS: 'ADD_LIST_SUCCESS',

    REMOVE_LIST_START: 'REMOVE_LIST_START',
    REMOVE_LIST_FAIL: 'REMOVE_LIST_FAIL',
    REMOVE_LIST_SUCCESS: 'REMOVE_LIST_SUCCESS',





    //Start and fail
    START: 'START',
    FAIL: 'FAIL',

    //Fetch boards
    FETCH: 'FETCH',

    //Add board
    ADD_BOARD: 'ADD_BOARD',
    ADD_LIST: 'ADD_LIST',
    ADD_CARD: 'ADD_CARD',

    //Remove boards
    REMOVE: 'REMOVE',
    REMOVE_CARD: 'REMOVE_CARD',
    REMOVE_CHILDREN: 'REMOVE_CHILDREN',
};
