export const Actions = {
    //Board
    FETCH_BOARD_START: 'FETCH_BOARD_START',
    FETCH_BOARD_FAIL: 'FETCH_BOARD_FAIL',
    FETCH_BOARD_SUCCESS: 'FETCH_BOARD_SUCCESS',

    ADD_BOARD_START: 'ADD_BOARD_START',
    ADD_BOARD_FAIL: 'ADD_BOARD_FAIL',
    ADD_BOARD_SUCCESS: 'ADD_BOARD_SUCCESS',

    REMOVE_BOARD_START: 'REMOVE_BOARD_START',
    REMOVE_BOARD_FAIL: 'REMOVE_BOARD_FAIL',
    REMOVE_BOARD_SUCCESS: 'REMOVE_BOARD_SUCCESS',

    //Single Board
    FETCH_SINGLE_BOARD_START: 'FETCH_SINGLE_BOARD_START',
    FETCH_SINGLE_BOARD_FAIL: 'FETCH_SINGLE_BOARD_FAIL',
    FETCH_SINGLE_BOARD_SUCCESS: 'FETCH_SINGLE_BOARD_SUCCESS',

    //List
    ADD_LIST_START: 'ADD_LIST_START',
    ADD_LIST_FAIL: 'ADD_LIST_FAIL',
    ADD_LIST_SUCCESS: 'ADD_LIST_SUCCESS',

    REMOVE_LIST_START: 'REMOVE_LIST_START',
    REMOVE_LIST_FAIL: 'REMOVE_LIST_FAIL',
    REMOVE_LIST_SUCCESS: 'REMOVE_LIST_SUCCESS',

    EDIT_LIST_START: 'EDIT_LIST_START',
    EDIT_LIST_FAIL: 'EDIT_LIST_FAIL',
    EDIT_LIST_SUCCESS: 'EDIT_LIST_SUCCESS',

    //Card
    ADD_CARD_START: 'ADD_CARD_START',
    ADD_CARD_FAIL: 'ADD_CARD_FAIL',
    ADD_CARD_SUCCESS: 'ADD_CARD_SUCCESS',

    REMOVE_CARD_START: 'REMOVE_CARD_START',
    REMOVE_CARD_FAIL: 'REMOVE_CARD_FAIL',
    REMOVE_CARD_SUCCESS: 'REMOVE_CARD_SUCCESS',

    OPEN_CARD_MODAL_START: 'OPEN_CARD_MODAL_START',
    OPEN_CARD_MODAL_FAIL: 'OPEN_CARD_MODAL_FAIL',
    OPEN_CARD_MODAL_SUCCESS: 'OPEN_CARD_MODAL_SUCCESS',
    CLOSE_CARD_MODAL: 'CLOSE_CARD_MODAL',

    HANDLE_CARD_DESC: 'HANDLE_CARD_DESC',
    HANDLE_CARD_NAME: 'HANDLE_CARD_NAME',
    HANDLE_CARD_IMAGE: 'HANDLE_CARD_IMAGE',

    REMOVE_CARD_IMAGE: 'REMOVE_CARD_IMAGE',
    REMOVE_CARD_IMAGE_AFTER: 'REMOVE_CARD_IMAGE_AFTER',

    ADD_IMAGE_START: 'ADD_IMAGE_START',
    ADD_IMAGE_FAIL: 'ADD_IMAGE_FAIL',
    ADD_IMAGE_SUCCESS: 'ADD_IMAGE_SUCCESS',

    SAVE_CARD_DATA_START: 'SAVE_CARD_DATA_START',
    SAVE_CARD_DATA_FAIL: 'SAVE_CARD_DATA_FAIL',
    SAVE_CARD_DATA_SUCCESS: 'SAVE_CARD_DATA_SUCCESS',
    SAVE_CARD_DATA_SUCCESS_AFTER: 'SAVE_CARD_DATA_SUCCESS_AFTER',





    //Start and fail
    START: 'START',
    FAIL: 'FAIL',

    //Fetch boards
    FETCH: 'FETCH',

    //Add board
    ADD_BOARD: 'ADD_BOARD',
    ADD_LIST: 'ADD_LIST',
    ADD_CARD: 'ADD_CARD',

    //Remove boards
    REMOVE: 'REMOVE',
    REMOVE_CARD: 'REMOVE_CARD',
    REMOVE_CHILDREN: 'REMOVE_CHILDREN',
};
